# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=${APP_JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
app.razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_Obz1IQlDtOvh1b}
app.razorpay.key-secret=${RAZORPAY_KEY_SECRET:emEgTjBai7QkbElaxGGDUZc5}

# Server port
server.port=8081
